-- Phase 1 baseline schema: matches the User and Product entities as of this migration.
-- Never edit an applied migration; add a new V<n>__*.sql instead.
-- Note: enum columns carry CHECK constraints, so adding a Role or Category value needs a migration.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(255)                NOT NULL,
    email         VARCHAR(255)                NOT NULL,
    password_hash VARCHAR(255)                NOT NULL,
    role          VARCHAR(255)                NOT NULL,
    enabled       BOOLEAN                     NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'CUSTOMER'))
);

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255)                NOT NULL,
    description    VARCHAR(2000),
    price          NUMERIC(12, 2)              NOT NULL,
    category       VARCHAR(255)                NOT NULL,
    stock_quantity INTEGER                     NOT NULL,
    active         BOOLEAN                     NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT ck_products_category CHECK (category IN
        ('ELECTRONICS', 'FASHION', 'HOME_AND_KITCHEN', 'BEAUTY', 'GROCERIES', 'SPORTS', 'BOOKS'))
);
